services:
  hardfiles:
    container_name: hardfiles
    image: git.supernets.org/supernets/hardfiles:latest
    volumes:
      - "$PWD/files:/app/files"
      - "$PWD/www:/app/www"
      - "$PWD/config.toml:/app/config.toml"
    ports:
      - "5000:5000"