services:
  hardfiles:
    container_name: hardfiles
    build: .
    volumes:
      - ./files:/app/files
      - ./backgrounds:/app/backgrounds
      - ./config.toml:/app/config.toml
    ports:
      - "5000:5000"
    restart: unless-stopped
